# This is a basic workflow to help you get started with Actions

name: Getting Strated

# Controls when the workflow will run
on:
  push:
    branches: [ "main" ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build-on-windows:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    
      - name: Step 1 - checkout the main GitHub branch
        uses: actions/checkout@v3

      - name: Step 2 - log
        run: ls

      - name: Step 3 - Set up JDK1.8
        uses: actions/setup-java@v1
         with
           Java-version:1.8 
         
      - name: Step 4 - check
        run: |
         echo here is the windows ExecutionPolicy:
         Get-ExecutionPolicy
         
      - name: Step 6 - list
        run: env
        
 # This second job in this workflow is named biuls-on-ubuntu
  build-on-ubuntu:
     # This type of runner 
      runs-on: ubuntu-latest
      
      # Steps
      steps:
      
        - name: Step 1 - log 
          run: ls
        
        - name: Step 2 - Checkout
          uses: actions/checkout@v2
        
        - name: Setup JDK 1.8
          uses: actions/setup-java@v1
        
        - name: Step 4 - jakarta
          run: echo mvn -B package --file pom.xml
        
        - name: Step 5 - list
          run: env    
